# This is a basic workflow to help you get started with Actions

name: sign

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
      - '.github/**'
      - 'src/**'
      - 'package.json'
      - 'Dockerfile'
      - 'docker-compose.yml'

  # schedule:
    # - cron: '30 1 * * 1-5'
    # - cron: '30 10 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2
      
      # sign in server
      - uses: appleboy/ssh-action@master
        with:
          host: 111.67.197.101
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd /home/work/automatic-sign-in/
            git pull
            docker-compose down
            docker-compose up -d
            
      # Temporarily set ssh key
      # - name: set ssh key
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "${{secrets.FOR_SIGN_RSA}}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan "111.67.200.210" >> ~/.ssh/known_hosts

      # Send project file
      # - name: send
      #   run: |
      #     scp -i ~/.ssh/id_rsa -r src xt@111.67.200.210:/home/xt/signApp/
      #     scp -i ~/.ssh/id_rsa package.json xt@111.67.200.210:/home/xt/signApp/

      # Runs a set of commands using the runners shell
      # - name: deploy
        # run: |
        #   ssh work@111.67.200.210 "
        #     cd /home/work/automatic-sign-in/;
        #     git pull;
        #     docker-compose build auto-sign;
        #     docker-compose down;
        #     docker-compose up -d;
        #   "

      # delete ssh key
      # - name: delete
      #   run: rm -rf ~/.ssh/id_rsa